import type {
  CafeProfile,
  CartItem,
  GSTConfig,
  KOTTicket,
  MenuItem,
  OrderBill,
  StaffUser,
  Table,
  UserRole,
} from '../types/cms';

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000).toISOString();

const daysAgoAt = (days: number, hour: number, minute = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const STAFF_USERS: StaffUser[] = [
  {
    id: 'staff-admin',
    name: 'Ayan Roy',
    phone: '7596867727',
    password: '11112000',
    pin: '0000',
    role: 'ADMIN',
  },
  {
    id: 'staff-manager',
    name: 'Priya Sen',
    phone: '9876543210',
    password: 'RoastOps1',
    pin: '1111',
    role: 'MANAGER',
  },
  {
    id: 'staff-waiter',
    name: 'Riya Ghosh',
    phone: '9876543212',
    password: 'Waiter1',
    pin: '3333',
    role: 'WAITER',
  },
  {
    id: 'staff-chef',
    name: 'Arjun Das',
    phone: '9876543211',
    password: 'Chef1',
    pin: '2222',
    role: 'CHEF',
  },
];

export const DEMO_CREDENTIALS: Record<UserRole, { phone: string; password: string }> = {
  ADMIN: { phone: '7596867727', password: '11112000' },
  MANAGER: { phone: '9876543210', password: 'RoastOps1' },
  WAITER: { phone: '9876543212', password: 'Waiter1' },
  CHEF: { phone: '9876543211', password: 'Chef1' },
};

export const DEFAULT_CAFE_PROFILE: CafeProfile = {
  name: 'RoastOps Cafe',
  address: '12 Park Street, near Park Circus',
  city: 'Kolkata',
  phone: '03340001106',
  email: 'hello@roastops.cafe',
  upiId: 'roastops@upi',
};

export const DEFAULT_GST_CONFIG: GSTConfig = {
  enabled: true,
  gstin: '19AAAAA0000A1Z5',
  cgstPercent: 2.5,
  sgstPercent: 2.5,
};

export const MENU_CATEGORIES = [
  'Coffee',
  'Starter',
  'Meal',
  'Dessert',
  'Cold Drinks',
  'Breakfast',
  'Seasonal',
] as const;

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-cappuccino',
    name: 'House Cappuccino',
    category: 'Coffee',
    description: 'Double shot with steamed milk and a dense crema cap.',
    imageKey: 'cappuccino',
    isMeal: false,
    fullPlatePrice: 190,
    isOutOfStock: false,
  },
  {
    id: 'item-espresso',
    name: 'Double Espresso',
    category: 'Coffee',
    description: 'Short, intense pull from single-origin beans.',
    imageKey: 'espresso',
    isMeal: false,
    fullPlatePrice: 150,
    isOutOfStock: false,
  },
  {
    id: 'item-garlic-toast',
    name: 'Chilli Garlic Toast',
    category: 'Starter',
    description: 'Sourdough, roasted garlic butter, chilli flakes.',
    imageKey: 'garlic-toast',
    isMeal: false,
    fullPlatePrice: 170,
    isOutOfStock: false,
  },
  {
    id: 'item-butter-chicken',
    name: 'Butter Chicken',
    category: 'Meal',
    description: 'Tandoori chicken in makhani gravy, served with rice.',
    imageKey: 'butter-chicken',
    isMeal: true,
    halfPlatePrice: 240,
    fullPlatePrice: 420,
    isOutOfStock: false,
  },
  {
    id: 'item-veg-biryani',
    name: 'Kolkata Veg Biryani',
    category: 'Meal',
    description: 'Awadhi-style dum biryani with potato and saffron.',
    imageKey: 'veg-biryani',
    isMeal: true,
    halfPlatePrice: 190,
    fullPlatePrice: 340,
    isOutOfStock: false,
  },
  {
    id: 'item-brownie',
    name: 'Dark Chocolate Brownie',
    category: 'Dessert',
    description: 'Warm walnut brownie with vanilla ice cream.',
    imageKey: 'brownie',
    isMeal: false,
    fullPlatePrice: 180,
    isOutOfStock: false,
  },
  {
    id: 'item-cold-brew',
    name: 'Cold Brew Fizz',
    category: 'Cold Drinks',
    description: '18-hour cold brew topped with soda and orange peel.',
    imageKey: 'cold-brew',
    isMeal: false,
    fullPlatePrice: 200,
    isOutOfStock: false,
  },
  {
    id: 'item-bhurji',
    name: 'Egg Bhurji Pav',
    category: 'Breakfast',
    description: 'Spiced scrambled eggs with buttered pav.',
    imageKey: 'bhurji',
    isMeal: false,
    fullPlatePrice: 160,
    isOutOfStock: false,
  },
  {
    id: 'item-aam-panna',
    name: 'Aam Panna Cooler',
    category: 'Seasonal',
    description: 'Raw mango cooler with mint and black salt.',
    imageKey: 'aam-panna',
    isMeal: false,
    fullPlatePrice: 150,
    isOutOfStock: true,
  },
  {
    id: 'item-mutton-kosha',
    name: 'Mutton Kosha',
    category: 'Meal',
    description: 'Slow-cooked Bengali mutton kosha, mustard oil finish.',
    imageKey: 'mutton-kosha',
    isMeal: true,
    halfPlatePrice: 280,
    fullPlatePrice: 490,
    isOutOfStock: false,
  },
];

const kot101CreatedAt = minutesAgo(4);
const kot102CreatedAt = minutesAgo(12);
const kot103CreatedAt = minutesAgo(18);

export const FLOOR_TABLES: Table[] = [
  {
    id: 'table-1',
    name: 'Table 1',
    seats: 2,
    status: 'AVAILABLE',
    currentKotIds: [],
    mergedTableIds: [],
  },
  {
    id: 'table-2',
    name: 'Table 2',
    seats: 2,
    status: 'OCCUPIED',
    occupiedAt: kot101CreatedAt,
    currentKotIds: ['kot-101'],
    mergedTableIds: [],
  },
  {
    id: 'table-3',
    name: 'Table 3',
    seats: 3,
    status: 'AVAILABLE',
    currentKotIds: [],
    mergedTableIds: [],
  },
  {
    id: 'table-4',
    name: 'Table 4',
    seats: 4,
    status: 'OCCUPIED',
    occupiedAt: kot102CreatedAt,
    currentKotIds: ['kot-102'],
    mergedTableIds: [],
  },
  {
    id: 'table-5',
    name: 'Table 5',
    seats: 4,
    status: 'NEEDS_CLEANING',
    currentKotIds: [],
    mergedTableIds: [],
  },
  {
    id: 'table-6',
    name: 'Table 6',
    seats: 4,
    status: 'AVAILABLE',
    currentKotIds: [],
    mergedTableIds: [],
  },
  {
    id: 'table-7',
    name: 'Table 7',
    seats: 6,
    status: 'OCCUPIED',
    occupiedAt: kot103CreatedAt,
    currentKotIds: ['kot-103'],
    mergedTableIds: [],
  },
  {
    id: 'table-8',
    name: 'Table 8',
    seats: 6,
    status: 'NEEDS_CLEANING',
    currentKotIds: [],
    mergedTableIds: [],
  },
];

const kotItems101: CartItem[] = [
  {
    id: 'kot-101-line-1',
    menuItemId: 'item-cappuccino',
    name: 'House Cappuccino',
    imageKey: 'cappuccino',
    quantity: 2,
    portion: 'FULL',
    unitPrice: 190,
    kitchenNotes: 'Extra hot',
  },
  {
    id: 'kot-101-line-2',
    menuItemId: 'item-garlic-toast',
    name: 'Chilli Garlic Toast',
    imageKey: 'garlic-toast',
    quantity: 1,
    portion: 'FULL',
    unitPrice: 170,
    kitchenNotes: 'No garlic on one slice',
  },
];

const kotItems102: CartItem[] = [
  {
    id: 'kot-102-line-1',
    menuItemId: 'item-butter-chicken',
    name: 'Butter Chicken',
    imageKey: 'butter-chicken',
    quantity: 1,
    portion: 'FULL',
    unitPrice: 420,
    kitchenNotes: 'Less gravy',
  },
  {
    id: 'kot-102-line-2',
    menuItemId: 'item-veg-biryani',
    name: 'Kolkata Veg Biryani',
    imageKey: 'veg-biryani',
    quantity: 1,
    portion: 'HALF',
    unitPrice: 190,
    kitchenNotes: '',
  },
];

const kotItems103: CartItem[] = [
  {
    id: 'kot-103-line-1',
    menuItemId: 'item-mutton-kosha',
    name: 'Mutton Kosha',
    imageKey: 'mutton-kosha',
    quantity: 2,
    portion: 'FULL',
    unitPrice: 490,
    kitchenNotes: 'Extra spicy',
  },
  {
    id: 'kot-103-line-2',
    menuItemId: 'item-cold-brew',
    name: 'Cold Brew Fizz',
    imageKey: 'cold-brew',
    quantity: 2,
    portion: 'FULL',
    unitPrice: 200,
    kitchenNotes: 'Less sugar',
  },
];

export const ACTIVE_KOT_TICKETS: KOTTicket[] = [
  {
    id: 'kot-101',
    ticketNumber: 'KOT-101',
    tableId: 'table-2',
    tableName: 'Table 2',
    items: kotItems101,
    status: 'RECEIVED',
    createdAt: kot101CreatedAt,
    struckItemIds: [],
    createdByStaffId: 'staff-waiter',
  },
  {
    id: 'kot-102',
    ticketNumber: 'KOT-102',
    tableId: 'table-4',
    tableName: 'Table 4',
    items: kotItems102,
    status: 'IN_PREP',
    createdAt: kot102CreatedAt,
    struckItemIds: ['kot-102-line-2'],
    createdByStaffId: 'staff-chef',
  },
  {
    id: 'kot-103',
    ticketNumber: 'KOT-103',
    tableId: 'table-7',
    tableName: 'Table 7',
    items: kotItems103,
    status: 'READY',
    createdAt: kot103CreatedAt,
    struckItemIds: ['kot-103-line-1', 'kot-103-line-2'],
    createdByStaffId: 'staff-waiter',
  },
];

export const COMPLETED_BILLS: OrderBill[] = [
  {
    id: 'bill-1001',
    billNumber: 'BILL-1001',
    tableId: 'table-1',
    tableName: 'Table 1',
    items: [
      {
        id: 'bill-1001-line-1',
        menuItemId: 'item-cappuccino',
        name: 'House Cappuccino',
        imageKey: 'cappuccino',
        quantity: 2,
        portion: 'FULL',
        unitPrice: 190,
        kitchenNotes: '',
      },
      {
        id: 'bill-1001-line-2',
        menuItemId: 'item-bhurji',
        name: 'Egg Bhurji Pav',
        imageKey: 'bhurji',
        quantity: 1,
        portion: 'FULL',
        unitPrice: 160,
        kitchenNotes: '',
      },
    ],
    subtotal: 540,
    cgstAmount: 13.5,
    sgstAmount: 13.5,
    total: 567,
    paymentMethod: 'CASH',
    splitCount: 1,
    settledAt: daysAgoAt(0, 9, 20),
    settledByStaffId: 'staff-chef',
  },
  {
    id: 'bill-1002',
    billNumber: 'BILL-1002',
    tableId: 'table-3',
    tableName: 'Table 3',
    items: [
      {
        id: 'bill-1002-line-1',
        menuItemId: 'item-butter-chicken',
        name: 'Butter Chicken',
        imageKey: 'butter-chicken',
        quantity: 1,
        portion: 'FULL',
        unitPrice: 420,
        kitchenNotes: '',
      },
      {
        id: 'bill-1002-line-2',
        menuItemId: 'item-cold-brew',
        name: 'Cold Brew Fizz',
        imageKey: 'cold-brew',
        quantity: 1,
        portion: 'FULL',
        unitPrice: 200,
        kitchenNotes: '',
      },
    ],
    subtotal: 620,
    cgstAmount: 15.5,
    sgstAmount: 15.5,
    total: 651,
    paymentMethod: 'UPI',
    splitCount: 2,
    settledAt: daysAgoAt(0, 13, 45),
    settledByStaffId: 'staff-chef',
    upiString: 'upi://pay?pa=roastops@upi&am=651',
  },
  {
    id: 'bill-1003',
    billNumber: 'BILL-1003',
    tableId: 'table-6',
    tableName: 'Table 6',
    items: [
      {
        id: 'bill-1003-line-1',
        menuItemId: 'item-veg-biryani',
        name: 'Kolkata Veg Biryani',
        imageKey: 'veg-biryani',
        quantity: 2,
        portion: 'FULL',
        unitPrice: 340,
        kitchenNotes: '',
      },
      {
        id: 'bill-1003-line-2',
        menuItemId: 'item-brownie',
        name: 'Dark Chocolate Brownie',
        imageKey: 'brownie',
        quantity: 1,
        portion: 'FULL',
        unitPrice: 180,
        kitchenNotes: '',
      },
    ],
    subtotal: 860,
    cgstAmount: 21.5,
    sgstAmount: 21.5,
    total: 903,
    paymentMethod: 'CARD',
    splitCount: 1,
    settledAt: daysAgoAt(1, 20, 10),
    settledByStaffId: 'staff-manager',
  },
  {
    id: 'bill-1004',
    billNumber: 'BILL-1004',
    tableId: 'table-4',
    tableName: 'Table 4',
    items: [
      {
        id: 'bill-1004-line-1',
        menuItemId: 'item-mutton-kosha',
        name: 'Mutton Kosha',
        imageKey: 'mutton-kosha',
        quantity: 1,
        portion: 'HALF',
        unitPrice: 280,
        kitchenNotes: '',
      },
      {
        id: 'bill-1004-line-2',
        menuItemId: 'item-cappuccino',
        name: 'House Cappuccino',
        imageKey: 'cappuccino',
        quantity: 3,
        portion: 'FULL',
        unitPrice: 190,
        kitchenNotes: '',
      },
    ],
    subtotal: 850,
    cgstAmount: 21.25,
    sgstAmount: 21.25,
    total: 892.5,
    paymentMethod: 'UPI',
    splitCount: 3,
    settledAt: daysAgoAt(4, 18, 30),
    settledByStaffId: 'staff-chef',
    upiString: 'upi://pay?pa=roastops@upi&am=892.5',
  },
  {
    id: 'bill-1005',
    billNumber: 'BILL-1005',
    tableId: 'table-8',
    tableName: 'Table 8',
    items: [
      {
        id: 'bill-1005-line-1',
        menuItemId: 'item-bhurji',
        name: 'Egg Bhurji Pav',
        imageKey: 'bhurji',
        quantity: 4,
        portion: 'FULL',
        unitPrice: 160,
        kitchenNotes: '',
      },
      {
        id: 'bill-1005-line-2',
        menuItemId: 'item-espresso',
        name: 'Double Espresso',
        imageKey: 'espresso',
        quantity: 2,
        portion: 'FULL',
        unitPrice: 150,
        kitchenNotes: '',
      },
    ],
    subtotal: 940,
    cgstAmount: 23.5,
    sgstAmount: 23.5,
    total: 987,
    paymentMethod: 'CASH',
    splitCount: 4,
    settledAt: daysAgoAt(6, 8, 50),
    settledByStaffId: 'staff-manager',
  },
];
